const manifest = {
  colors: {},
  semanticColors: {},
  aspectRatios: { mq: true },
  backgroundSize: { mq: true },
  backgroundPosition: { mq: true },
  borders: { mq: true },
  borderStyle: { mq: true },
  boxShadow: { mq: true },
  spacing: { mq: true, print: true },
  coordinates: { mq: true },
  clears: { mq: true, print: true },
  display: { mq: true, print: true },
  flexbox: { mq: true, print: true },
  floats: { mq: true, print: true },
  fontStyle: { mq: true, print: true },
  heights: { mq: true },
  letterSpacing: { mq: true, print: true },
  lineHeight: { mq: true, print: true },
  opacity: { mq: true },
  rotations: { mq: true },
  outlines: { mq: true },
  overflow: { mq: true },
  position: { mq: true },
  textDecoration: { mq: true, print: true },
  textAlign: { mq: true, print: true },
  textTransform: { mq: true, print: true },
  typeScale: { mq: true, print: true },
  typography: { mq: true, print: true },
  fontWeight: { mq: true, print: true },
  visibility: { mq: true, print: true },
  whiteSpace: { mq: true, print: true },
  widths: { mq: true, print: true },
  print: { print: true },
  boxSizing: {},
  code: {},
  fontFamily: {},
  forms: {},
  links: {},
  lists: {},
  images: {},
  normalize: {},
  hovers: {},
  verticalAlign: {},
  utilities: {},
  zIndex: {},
};

export default manifest;
